# Generated by Django 5.2.17 on 2026-08-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
