# Generated by Django 5.2.17 on 2026-08-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ai_priority',
        ),
    ]
