# Generated by Django 5.2.17 on 2026-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_remove_complaint_ai_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.URLField(),
        ),
    ]
