# Generated by Django 5.2.17 on 2026-09-10 07:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaintimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
