# Generated by Django 5.2.17 on 2026-09-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_complaint_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_complaints', to='complaint.complaint')),
                ('similar_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by', to='complaint.complaint')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('complaint', 'similar_complaint'), name='unique_complaint_similarity')],
            },
        ),
    ]
