# Generated by Django 5.2.17 on 2026-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('officer', 'Officer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
