# Generated by Django 5.2.17 on 2026-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_officerprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
