# Generated by Django 5.2.17 on 2026-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
