# Generated by Django 5.2.17 on 2026-08-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_officerprofile_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
